# Generated by Django 5.2.7 on 2025-11-09 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
