# Generated by Django 5.2.7 on 2025-11-09 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_alter_course_options_alter_lesson_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "course",
                "verbose_name_plural": "courses",
            },
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["created_at"],
                "verbose_name": "lesson",
                "verbose_name_plural": "lessons",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="цена"
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="сумма оплаты"
                    ),
                ),
                (
                    "stripe_product_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID продукта в Stripe",
                    ),
                ),
                (
                    "stripe_price_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID цены в Stripe",
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="ID сессии в Stripe",
                    ),
                ),
                (
                    "payment_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="ссылка для оплаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("processing", "Обрабатывается"),
                            ("succeeded", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                            ("canceled", "Отменен"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="статус оплаты",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="обновлен"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="materials.course",
                        verbose_name="курс",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "платеж",
                "verbose_name_plural": "платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
